Checkout Refactoring and Comprehensive Testing Setup (#8)
* Refactor TebexCheckout usage and event handling

This commit refactors the UseTebexCheckout function to improve event handling. It ensures that event handlers for Tebex events are only registered once and are properly cleaned up to prevent multiple triggers. It also adds checks to ensure that window.Tebex exists before trying to access its properties. Documentation for this component is pending until refactor is satisfactory.

* Introduced new utility function to handle chain operations sequentially, centralized store interaction, and added more optimistic UI

- Introduced useFetecherWithPromise utility to ensure that each operation waits for the previous one to complete successfully before proceeding.
- Setup local state to control flow between operations. Ensured each submission is a new transaction and not a continuation of the previous state.
- UseTebexCheckout is now setup to be managed separately and ensured it is only called once all prerequisites are fulfilled.
- Update localBasketId / localPackages directly after creation / addition, ensuring availability for the next step.
- Use condition to check if the basket ID is set and the package has been added before attempting checkout.
- Added try-catch block logs.

Tests made:
- Without a basket: Confirm that creating a basket, adding a package, and initiating checkout occur in order.
- With a basket but no package: Confirm that it skips basket creation, adds the package, and initiates checkout.
- With a basket and a package: Confirm that it skips to initiating checkout directly.

* Refactoring for Readability

Broke it down into smaller functions.

* Implemented comprehensive testing setup and added unit tests for LoginForm.

- Upgraded Remix to version 2.9.1.
- Introduced and configured Mock Service Worker (MSW) for Remix.
- Installed Playwright (configuration pending).
- Added Vitest and configured test scripts in npm.
- Installed Faker for generating test data.
- Installed Jest and Happy DOM for testing environments, with JSDOM currently in use.
- Configured MSW working directory and updated Vite config to include client and Vitest references.
- Updated plugins to check for Vitest process environment for Remix().
- Added a test section setting globals, environment (JSDOM), and setup for loading a test environment.
- Updated tsconfig.js and included setup file and Vite/added Jest and Vitest/globals in the types part of the compiler options.
- Defined module Vitest within test/setup-test-env.ts to extend Jest matchers.
- Configured Remix config foundation to explicitly state server module format as ESM and ignored route files.
- Created env.d.ts with our references (vite/client, remix-run/node).
- Added a simple store unit test (unit/routes/store.tsx) for future conversion to Playwright end-to-end testing.
- Set up tests for AuthForms and LoginForm components to demonstrate testing capabilities.
- Added error boundary fallback.
- Created a mocks folder for MSW under the app folder for API mocking.
- Set up server-side integration for MSW.
- Added data-testid="login-form" to ValidatedForm in LoginForm.tsx for testing purposes.

The LoginForm tests cover the following scenarios:
- Checking if the form exists.
- Checking if the email and password inputs exist.
- Typing into the email and password fields and checking if the inputs are updated.
- Submitting the form.
- Displaying an invalid email message when the email is invalid and the password is valid.
- Displaying an invalid password message when the password is missing and the email is valid.

* Manually required eslint changes

Needed to fix some eslint related errors manually for PR requirement

diff --git a/.github/workflows/eslint_prettier_pr_check.yml b/.github/workflows/eslint_prettier_pr_check.yml
--- a/.github/workflows/eslint_prettier_pr_check.yml
+++ b/.github/workflows/eslint_prettier_pr_check.yml
@@ -12,62 +12,62 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-    - name: Checkout code
-      uses: actions/checkout@v3
-      with:
-        ref: ${{ github.head_ref }}  # This makes sure we're checking out the head of the branch involved in the PR
-        fetch-depth: 0  # Important to fetch all history for commits comparison
+      - name: Checkout code
+        uses: actions/checkout@v3
+        with:
+          ref: ${{ github.head_ref }} # This makes sure we're checking out the head of the branch involved in the PR
+          fetch-depth: 0 # Important to fetch all history for commits comparison
 
-    - name: Setup Node.js
-      uses: actions/setup-node@v3
-      with:
-        node-version: '18'
-        cache: 'npm'
+      - name: Setup Node.js
+        uses: actions/setup-node@v3
+        with:
+          node-version: '18'
+          cache: 'npm'
 
-    - name: Install Dependencies
-      run: npm ci
+      - name: Install Dependencies
+        run: npm ci
 
-    - name: Run ESLint and Prettier for Code Formatting
-      run: npm run lint-and-format
-      # This command must exit with a non-zero status if there are errors that cannot be auto-fixed
+      - name: Run ESLint and Prettier for Code Formatting
+        run: npm run lint-and-format
+        # This command must exit with a non-zero status if there are errors that cannot be auto-fixed
 
-    - name: Check for Modified Files
-      id: git-check
-      run: |
-        if [[ `git status --porcelain` ]]; then
-          echo "changes_detected=true" >> $GITHUB_ENV
-        fi
+      - name: Check for Modified Files
+        id: git-check
+        run: |
+          if [[ `git status --porcelain` ]]; then
+            echo "changes_detected=true" >> $GITHUB_ENV
+          fi
 
-    - name: Avoid recursive workflow runs
-      run: |
-        if git log -1 --pretty=%B | grep -q 'Apply ESLint and Prettier fixes generated by GitHub Actions'; then
-          echo "Recursive commit detected - exiting!"
-          exit 0
-        fi
+      - name: Avoid recursive workflow runs
+        run: |
+          if git log -1 --pretty=%B | grep -q 'Apply ESLint and Prettier fixes generated by GitHub Actions'; then
+            echo "Recursive commit detected - exiting!"
+            exit 0
+          fi
 
-    - name: Commit and Push Changes if needed
-      if: env.changes_detected == 'true'
-      run: |
-        git config user.name github-actions
-        git config user.email github-actions@github.com
-        git add .
-        git restore --staged .github/
-        if git diff --cached --quiet; then
-          echo "No changes to commit after filtering out workflow changes."
-        else
-          git commit -m "Apply ESLint and Prettier fixes generated by GitHub Actions"
-          git push origin ${{ github.head_ref }} --force
-        fi
-      env:
-        GITHUB_TOKEN: ${{ secrets.FINE_GRAINED_PAT }}  # Using the PAT instead of GITHUB_TOKEN
+      - name: Commit and Push Changes if needed
+        if: env.changes_detected == 'true'
+        run: |
+          git config user.name github-actions
+          git config user.email github-actions@github.com
+          git add .
+          git restore --staged .github/
+          if git diff --cached --quiet; then
+            echo "No changes to commit after filtering out workflow changes."
+          else
+            git commit -m "Apply ESLint and Prettier fixes generated by GitHub Actions"
+            git push origin ${{ github.head_ref }} --force
+          fi
+        env:
+          GITHUB_TOKEN: ${{ secrets.FINE_GRAINED_PAT }} # Using the PAT instead of GITHUB_TOKEN
 
-    - name: Log Results
-      run: |
-        if [ "${{ job.status }}" == "success" ]; then
-          echo "ESLint checks completed successfully."
-          echo "Prettier formatting check completed successfully."
-          echo "All checks have passed successfully."
-        else
-          echo "Some checks have failed. Please review the annotations."
-          exit 1  # This ensures that the step explicitly fails if previous steps had issues.
-        fi
+      - name: Log Results
+        run: |
+          if [ "${{ job.status }}" == "success" ]; then
+            echo "ESLint checks completed successfully."
+            echo "Prettier formatting check completed successfully."
+            echo "All checks have passed successfully."
+          else
+            echo "Some checks have failed. Please review the annotations."
+            exit 1  # This ensures that the step explicitly fails if previous steps had issues.
+          fi
